SELECT DISTINCT ON (PARENTAL_RATING)
	M.PARENTAL_RATING  AS PARENTAL_RATING,
	M.TITLE AS MOVIE,
	R.GRADE AS GRADE
FROM 
	MOVIES M 
JOIN
	RATINGS R 
ON 
	M.ID = R.MOVIE_ID
WHERE (PARENTAL_RATING, GRADE) IN (
	SELECT PARENTAL_RATING, MAX(GRADE) AS MAX_GRADE
	FROM MOVIES
	JOIN RATINGS ON MOVIES.ID = RATINGS.MOVIE_ID
	GROUP BY PARENTAL_RATING 
) 
