SELECT DISTINCT ON (GENRE)
	M.GENRE AS GENRE,
	M.TITLE AS MOVIE,
	R.GRADE AS GRADE
FROM 
	MOVIES M 
JOIN
	RATINGS R 
ON 
	M.ID = R.MOVIE_ID
WHERE (GENRE, GRADE) IN (
	SELECT GENRE, MAX(GRADE) AS MAX_GRADE
	FROM MOVIES
	JOIN RATINGS ON MOVIES.ID = RATINGS.MOVIE_ID
	GROUP BY GENRE
);